# 测试配置文件
# @author <a href="https://github.com/cmrhyq">AlanHuang</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:\Code\stress-test\stress-test-data\resource\db\StressTest.db